apiVersion: v1
kind: PersistentVolume
metadata:
  name: miq-db
spec:
  capacity:
    storage: 15Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /var/lib/minishift/miq-db
  persistentVolumeReclaimPolicy: Retain
