apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    volume: ${PV}
  name: ${PV}
spec:
  accessModes:
  - ReadWriteOnce
  - ReadWriteMany
  - ReadOnlyMany
  capacity:
    storage: 100Gi
  hostPath:
    path: /var/lib/minishift/openshift.local.pv/${PV}
  persistentVolumeReclaimPolicy: Recycle
